trigger:
  branches:
    include:
    - 'master'
  tags:
    include:
    - 'v*'

# PR build config is manually overridden in Azure pipelines UI with different secrets
pr: none

jobs:
- job: docs
  dependsOn: [] # this removes the implicit dependency on previous stage and causes this to run in parallel.
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: CacheBeta@1
    inputs:
      key: 'format | ./WORKSPACE | **/*.bzl'
      path: $(Build.StagingDirectory)/repository_cache

  - script: ci/run_envoy_docker.sh 'ci/do_ci.sh docs'
    workingDirectory: $(Build.SourcesDirectory)
    env:
      ENVOY_DOCKER_BUILD_DIR: $(Build.StagingDirectory)
      BAZEL_REMOTE_CACHE: grpcs://remotebuildexecution.googleapis.com
      BAZEL_REMOTE_INSTANCE: projects/envoy-ci/instances/default_instance
      GCP_SERVICE_ACCOUNT_KEY: $(GcpServiceAccountKey)
    displayName: "Generate docs"

  - task: PublishCodeCoverageResults@1
    inputs:
      summaryFileLocation: "$(Build.SourcesDirectory)/coverage-with-data.xml"
      reportDirectory: "$(Build.StagingDirectory)/generated/docs"
